---
name: EasyGKits
main: AndreasHGK\EasyKits\EasyKits
version: 1.1.5
api:
- 3.9.0
load: POSTWORLD
author: IcyEndymion004
description: A gkit plugin
softdepend:
- EconomyAPI
- MultiEconomy
- PiggyCustomEnchants
permissions:
  Gkits:
    default: op
    description: easykits root permission
    children:
      Gkits.command:
        default: op
        description: easykits root command permission
        children:
          Gkits.command.kit:
            default: true
            description: permission for the /Gkit command
           Gkits.command.createkit:
            default: op
            description: permission for the /createGkit command
          Gkits.command.deletekit:
            default: op
            description: permission for the /deleteGkit command
          Gkits.command.ekimport:
            default: op
            description: permission for the /ekimport command
          Gkits.command.editkit:
            default: op
            description: permission for the /editGkit command
          Gkits.command.createcategory:
            default: op
            description: permission for the /createGkitcategory command
          Gkits.command.deletecategory:
            default: op
            description: permission for the /deleteGkitcategory command
          Gkits.command.givekit:
            default: op
            description: permission for the /giveGkit command
      Gkits.kit:
        default: op
        description: permission for specific kits
      Gkits.free:
        default: false
        description: claim kits for free
      Gkits.instant:
        default: false
        description: claim without a cooldown
      Gkits.category:
        default: op
        description: permission for specific categories
...
